export default {
  path:'/movie',
  component:()=>import('@/views/Movie'),
  children:[
    {
      path:'city',
      component:()=>import('@/components/City'),
    },
    {
      path:'nowplaying',
      component:()=>import('@/components/nowplaying'),
    },
    {
      path:'comming',
      component:()=>import('@/components/Comming'),
    },
    {
      path:'search',
      component:()=>import('@/components/Search'),
    },
    {
      path:'detail/1/:movieid',
      components:{
        default:()=>import('@/components/nowplaying'),
        detail:()=>import('@/views/Movie/detail')
      },
      props:{
        detail:true
      }
    },
    {
      path:'detail/2/:movieid',
      components:{
        default:()=>import('@/components/Comming'),
        detail:()=>import('@/views/Movie/detail')
      },
      props:{
        detail:true
      }
    },
    {
      path:'/movie',
      redirect:'/movie/nowplaying'
    }
  ]
}
